### PR TITLE
+ [3.0-RC-2] Add bossbar action but idk its working

### PR DESCRIPTION
**Pull request by Galaxy-VN**
I hope Score2 help me fix it <333

### CODE REVIEW

**Comment by Score2** [comment]
Thank you:)

**Comment by Score2** [comment]
I will try my best to support this action to 1.8

**Comment by Galaxy-VN** [comment]
> I will try my best to support this action to 1.8

thank you <333

**Comment by Galaxy-VN** [comment]
> I will try my best to support this action to 1.8

btw idk how the task thing on kotlin working could you fix it so it can be send to player and remove when out of stay ❤️

**Pull request merged**
